name: Deploy_localhost_AllInOne

on:
  push:
    branches: [ '**' ]
    tags-ignore: [ '**' ]


jobs:
  versioning:
    name: "Versioning"
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    outputs:
      version: ${{ steps.genver.outputs.version }}
    steps:
      - name: Get type of VM
        run: |
          lscpu
          uname -a
          grep MemTotal /proc/meminfo
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Generate Version
        id: genver
        run: |
          VERSION=$(docker run --rm -v $(pwd):/repo codacy/git-version /bin/git-version --folder=/repo --release-branch=release --dev-branch=main)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo $VERSION
          echo "Version :" >> $GITHUB_STEP_SUMMARY
          echo "$VERSION" >> $GITHUB_STEP_SUMMARY
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install terraform
        run: sh tools/install/terraform.sh

      - name: Check Format
        run: terraform fmt -check -recursive -diff

